# Generated by Django 5.1 on 2024-11-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_artist"),
    ]

    operations = [
        migrations.AddField(
            model_name="wrappedhistory",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="song_preview",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="artist",
            name="top_song",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RemoveField(
            model_name="wrappedhistory",
            name="artists",
        ),
        migrations.AddField(
            model_name="wrappedhistory",
            name="artists",
            field=models.ManyToManyField(to="accounts.artist"),
        ),
    ]
